#!/usr/bin/env bash
# Builds the bridge, registers the native messaging host with every installed
# Chromium browser, and registers the MCP server with Claude Code.
# Idempotent: re-run it after pulling changes or switching Node versions.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/lib.sh
source "$REPO/scripts/lib.sh"

EXTENSION_ID="$(tr -d '[:space:]' < "$REPO/extension/extension-id.txt")"
if [[ ! "$EXTENSION_ID" =~ ^[a-p]{32}$ ]]; then
  echo "extension/extension-id.txt does not hold a valid extension ID" >&2
  exit 1
fi

# Chrome starts native hosts without the user's shell PATH, so the wrapper
# needs an absolute node. A mise shim would not work there either: resolve it
# to the real binary, honouring this repo's mise.toml.
resolve_node() {
  local node=""
  if command -v mise > /dev/null; then
    node="$(cd "$REPO" && mise which node 2> /dev/null || true)"
  fi
  if [[ -z "$node" ]]; then
    node="$(command -v node || true)"
  fi
  if [[ -z "$node" ]]; then
    echo "node not found; install Node 24 or newer (mise install, in this repo)" >&2
    exit 1
  fi
  if [[ "$node" == */shims/* ]]; then
    echo "node resolves to a shim ($node); install mise or put a real node on PATH" >&2
    exit 1
  fi
  if ! "$node" -e 'process.exit(Number(process.versions.node.split(".")[0]) >= 24 ? 0 : 1)'; then
    echo "$node is $("$node" --version); Node 24 or newer is required" >&2
    exit 1
  fi
  printf '%s\n' "$node"
}

NODE="$(resolve_node)"
CBB="$REPO/host/dist/cbb.js"
# npm should run on the same node the wrapper will use.
PATH="$(dirname "$NODE"):$PATH"
export PATH

echo "==> Building with $NODE ($("$NODE" --version))"
if [[ ! -d "$REPO/node_modules" ]]; then
  (cd "$REPO" && npm ci)
fi
(cd "$REPO" && npm run build)

echo "==> Writing native host wrapper"
mkdir -p "$APP_DIR"
chmod 700 "$APP_DIR"
tmp="$(mktemp "$APP_DIR/.cbb-host.XXXXXX")"
{
  echo '#!/bin/sh'
  echo '# Generated by scripts/install.sh. Chrome runs this as the native messaging host.'
  printf 'exec %q %q host "$@"\n' "$NODE" "$CBB"
} > "$tmp"
chmod 755 "$tmp"
mv -f "$tmp" "$WRAPPER"
echo "    $WRAPPER"

echo "==> Registering native messaging host $HOST_NAME"
# JSON.stringify escapes the path properly, whatever it contains.
# shellcheck disable=SC2016 # the single-quoted program is JavaScript
manifest="$("$NODE" -e '
  const [name, path, id] = process.argv.slice(1);
  process.stdout.write(JSON.stringify({
    name,
    description: "Claude Browser Bridge native host",
    path,
    type: "stdio",
    allowed_origins: [`chrome-extension://${id}/`],
  }, null, 2) + "\n");
' "$HOST_NAME" "$WRAPPER" "$EXTENSION_ID")"

configured=0
for entry in "${BROWSERS[@]}"; do
  data_dir="$BROWSER_ROOT/${entry%%|*}"
  label="${entry#*|}"
  [[ -d "$data_dir" ]] || continue
  mkdir -p "$data_dir/NativeMessagingHosts"
  printf '%s\n' "$manifest" > "$data_dir/NativeMessagingHosts/$MANIFEST_NAME"
  echo "    $label: $data_dir/NativeMessagingHosts/$MANIFEST_NAME"
  configured=$((configured + 1))
done
if [[ "$configured" -eq 0 ]]; then
  echo "    No Chromium browser data directory found; start your browser once and re-run." >&2
fi

echo "==> Registering MCP server $MCP_NAME with Claude Code"
if command -v claude > /dev/null; then
  claude mcp remove --scope user "$MCP_NAME" > /dev/null 2>&1 || true
  claude mcp add --scope user "$MCP_NAME" -- "$NODE" "$CBB" mcp
else
  echo "    claude not on PATH; register it yourself:"
  echo "    claude mcp add --scope user $MCP_NAME -- $NODE $CBB mcp"
fi

cat << EOF

Done. Next steps:
  1. Open chrome://extensions, turn on Developer mode, click "Load unpacked"
     and pick $REPO/extension/dist
     (the ID should read $EXTENSION_ID).
  2. For mods (persistent user scripts), turn on "Allow User Scripts" on the
     extension's Details page: chrome://extensions/?id=$EXTENSION_ID
  3. Restart Claude Code so it picks up the $MCP_NAME MCP server, then ask it
     to run bridge_status.
EOF
